import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import Header from '../components/Header/Header'
import HealthSide from '@/components/HealthSide/HealthSide'
import StaticBar from './../components/StaticBar/StaticBar';
import BestBody from '@/components/BestBody/BestBody'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>IRD FOUNDATION</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <div>
      <Header></Header>
      <HealthSide></HealthSide>
      <StaticBar></StaticBar>
      <BestBody></BestBody>
   </div>
    </>
  )
}
